#!/usr/bin/env bash

# Vérification de la présence d'un argument
if [ -z "$1" ]; 
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
# Ping de l'adresse IP 5 fois
ping -c 5 "$1"
